project:
  type: website

website:
  title: "Xinyuan Huang"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: cv.qmd
        text: CV

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true